//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Cp.Data.Mapping
{
    public partial class MonthlyEvaluationMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cp.Data.Entities.MonthlyEvaluation>
    {
        public MonthlyEvaluationMap()
        {
            // table
            ToTable("MonthlyEvaluation", "dbo");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.Category)
                .HasColumnName("Category")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.UserId)
                .HasColumnName("UserId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.OrgId)
                .HasColumnName("OrgId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.EvaluateYear)
                .HasColumnName("EvaluateYear")
                .IsOptional();
            Property(t => t.EvaluateMonth)
                .HasColumnName("EvaluateMonth")
                .IsOptional();
            Property(t => t.Score)
                .HasColumnName("Score")
                .HasPrecision(18, 2)
                .IsOptional();
            Property(t => t.Creator)
                .HasColumnName("Creator")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.Created)
                .HasColumnName("Created")
                .IsOptional();
            Property(t => t.Updated)
                .HasColumnName("Updated")
                .IsOptional();
            Property(t => t.Grade)
                .HasColumnName("Grade")
                .IsOptional();
            Property(t => t.Notes)
                .HasColumnName("Notes")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.LessReason)
                .HasColumnName("LessReason")
                .HasMaxLength(255)
                .IsOptional();

            // Relationships
        }
    }
}
