//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Cp.Data.Mapping
{
    public partial class PerformanceAppraisalMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cp.Data.Entities.PerformanceAppraisal>
    {
        public PerformanceAppraisalMap()
        {
            // table
            ToTable("PerformanceAppraisal", "dbo");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.AccessmentScore)
                .HasColumnName("AccessmentScore")
                .HasPrecision(18, 2)
                .IsRequired();
            Property(t => t.RatersId)
                .HasColumnName("RatersId")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.RatersName)
                .HasColumnName("RatersName")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.JudgeId)
                .HasColumnName("JudgeId")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.JudgeName)
                .HasColumnName("JudgeName")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.Optime)
                .HasColumnName("Optime")
                .IsRequired();
            Property(t => t.State)
                .HasColumnName("State")
                .HasMaxLength(50)
                .IsRequired();

            // Relationships
        }
    }
}

