//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Cp.Data.Mapping
{
    public partial class UserMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cp.Data.Entities.User>
    {
        public UserMap()
        {
            // table
            ToTable("User", "dbo");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.Account)
                .HasColumnName("Account")
                .HasMaxLength(255)
                .IsRequired();
            Property(t => t.Password)
                .HasColumnName("Password")
                .HasMaxLength(255)
                .IsRequired();
            Property(t => t.Name)
                .HasColumnName("Name")
                .HasMaxLength(255)
                .IsRequired();
            Property(t => t.Sex)
                .HasColumnName("Sex")
                .IsRequired();
            Property(t => t.Status)
                .HasColumnName("Status")
                .IsRequired();
            Property(t => t.BizCode)
                .HasColumnName("BizCode")
                .HasMaxLength(255)
                .IsRequired();
            Property(t => t.CreateTime)
                .HasColumnName("CreateTime")
                .IsRequired();
            Property(t => t.CrateId)
                .HasColumnName("CrateId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.TypeName)
                .HasColumnName("TypeName")
                .HasMaxLength(20)
                .IsOptional();
            Property(t => t.TypeId)
                .HasColumnName("TypeId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.Age)
                .HasColumnName("Age")
                .IsOptional();
            Property(t => t.XRank)
                .HasColumnName("XRank")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.ZRank)
                .HasColumnName("ZRank")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.CardId)
                .HasColumnName("CardId")
                .HasMaxLength(50)
                .IsOptional();

            // Relationships
        }
    }
}
