//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class DepartmentMonthlyEvaluation : Entity
    {
        public DepartmentMonthlyEvaluation()
        {
          this.OrgId= string.Empty;
          this.Creator= string.Empty;
          this.Created= DateTime.Now;
          this.Updated= DateTime.Now;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <summary>
        /// 组织结构id
        /// </summary>
        [Required(AllowEmptyStrings = false, ErrorMessage = "请选择部门")]
        public string OrgId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? EvaluateYear { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? EvaluateMonth { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Required(AllowEmptyStrings = false, ErrorMessage = "请录入分数")]
        [Range(minimum: 0.00, maximum: 100, ErrorMessage = "请录入正确的分数;0-100分")]
        public decimal? Score { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Creator { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? Created { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? Updated { get; set; }

    }
}