//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel.DataAnnotations;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class EvaluateAverageScore : Entity
    {
        public EvaluateAverageScore()
        {
            this.Id = string.Empty;
            this.UserId = string.Empty;
            this.OrgId = string.Empty;
            this.Creator = string.Empty;
            this.Created = DateTime.Now;
            this.Updated = DateTime.Now;
        }

        /// <summary>
	    /// 用户id
	    /// </summary>
        [Required(AllowEmptyStrings =false,ErrorMessage ="请选择打分用户")]
        public string UserId { get; set; }
        /// <summary>
	    /// 组织结构id
	    /// </summary>
        [Required(AllowEmptyStrings = false, ErrorMessage = "请选择打分用户所在组织")]
        public string OrgId { get; set; }
        /// <summary>
	    /// 评价年份
	    /// </summary>
        public int? EvaluateYear { get; set; }
        /// <summary>
	    /// 评价月份
	    /// </summary>
        public int? EvaluateMonth { get; set; }
        /// <summary>
	    /// 得分
	    /// </summary>
        [Required(AllowEmptyStrings = false, ErrorMessage = "请录入分数")]
        [Range(minimum: 0.00, maximum: 100, ErrorMessage = "请录入正确的分数;0-100分")]
        public decimal? Score { get; set; }
        /// <summary>
        /// 创建者
        /// </summary>
        public string Creator { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? Created { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? Updated { get; set; }

    }
}