//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace Cp.Data.Entities
{
    /// <summary>
	/// 
	/// </summary>
    public partial class PerformanceAppraisal : Entity
    {
        public PerformanceAppraisal()
        {
          this.AccessmentScore= 0;
          this.RatersId= string.Empty;
          this.RatersName= string.Empty;
          this.JudgeId= string.Empty;
          this.JudgeName= string.Empty;
          this.Optime= DateTime.Now;
          this.State= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public decimal AccessmentScore { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string RatersId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string RatersName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string JudgeId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string JudgeName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime Optime { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string State { get; set; }

    }
}