//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class Test : Entity
    {
        public Test()
        {
          this.Data1= string.Empty;
          this.Data2= string.Empty;
          this.Data3= string.Empty;
          this.Checkboxs0= 0;
          this.Data7= string.Empty;
          this.Data8= string.Empty;
          this.Data9= string.Empty;
          this.Data10= string.Empty;
          this.Data11= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string Data1 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Data2 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Data3 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int Checkboxs0 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Data7 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Data8 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Data9 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Data10 { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Data11 { get; set; }

    }
}