//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OpenAuth.Repository.Mapping
{
    public partial class EvaluateAverageScoreMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<OpenAuth.Repository.Domain.EvaluateAverageScore>
    {
        public EvaluateAverageScoreMap()
        {
            // table
            ToTable("EvaluateAverageScore", "dbo");

            // keys

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.UserId)
                .HasColumnName("UserId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.OrgId)
                .HasColumnName("OrgId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.Creator)
                .HasColumnName("Creator")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.EvaluateYear)
                .HasColumnName("EvaluateYear")
                .IsOptional();
            Property(t => t.EvaluateMonth)
                .HasColumnName("EvaluateMonth")
                .IsOptional();
            Property(t => t.Score)
                .HasColumnName("Score")
                .HasPrecision(18, 2)
                .IsOptional();
            Property(t => t.Created)
                .HasColumnName("Created")
                .IsOptional();
            Property(t => t.Updated)
                .HasColumnName("Updated")
                .IsOptional();

            // Relationships
        }
    }
}
