//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OpenAuth.Repository.Mapping
{
    public partial class TestMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<OpenAuth.Repository.Domain.Test>
    {
        public TestMap()
        {
            // table
            ToTable("Test", "dbo");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.Data1)
                .HasColumnName("data_1")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.Data2)
                .HasColumnName("data_2")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.Data3)
                .HasColumnName("data_3")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.Checkboxs0)
                .HasColumnName("checkboxs_0")
                .IsRequired();
            Property(t => t.Data7)
                .HasColumnName("data_7")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.Data8)
                .HasColumnName("data_8")
                .HasMaxLength(255)
                .IsOptional();
            Property(t => t.Data9)
                .HasColumnName("data_9")
                .HasMaxLength(16)
                .IsOptional();
            Property(t => t.Data10)
                .HasColumnName("data_10")
                .HasMaxLength(16)
                .IsOptional();
            Property(t => t.Data11)
                .HasColumnName("data_11")
                .HasMaxLength(255)
                .IsOptional();

            // Relationships
        }
    }
}
